# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-23 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryPassword',
            fields=[
                ('usuario', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token_hash', models.TextField(blank=True, max_length=60)),
                ('date_expired', models.DateField(auto_now=True)),
                ('token_used', models.BooleanField(default=False)),
            ],
        ),
    ]
