version: '3'
# Uncomment for use postgres database
services:
  #db:
  #  image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    #depends_on:
    #  - db
